name: Log Sync Workflow

on:
  push:
    branches:
      - main  # The branch on which to trigger the action (e.g., main branch)

jobs:
  sync_logs:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3  # This checks out your code on the runner

      # Step 2: Set up Node.js (if your repo uses Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Set the Node.js version you are using

      # Step 3: Install dependencies (if needed)
      - name: Install dependencies
        run: npm install  # Adjust this if you're using other package managers

      # Step 4: Run your log sync script or any command
      - name: Run Log Sync Script
        run: |
          node path/to/your/log-sync-script.js  # Adjust path to your actual script

      # Step 5: Push changes back to GitHub (if needed)
      - name: Commit and Push Changes
        run: |
          git config user.name "Your GitHub Actions Bot"
          git config user.email "your-email@example.com"
          git add .  # Add all changed files
          git commit -m "Updated logs" || echo "No changes to commit"  # Commit if changes exist
          git push
