name: Sync Logs to GitHub

on:
  push:
    branches:
      - main
    paths:
      - 'logs/**'  # This watches the logs folder for changes

jobs:
  sync_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "sreeharikvsreehari9@gmail.com"
          git config --global user.name "IKKRU"

      - name: Add, commit, and push logs to GitHub
        run: |
          git add logs/
          git commit -m "Sync logs"
          git push
